/*
          # [Operação Estrutural e de Dados]
          Cria e povoa as tabelas de produtos (leagues, teams) e aprimora as tabelas existentes.

          ## Query Description: Este script realiza uma grande atualização na estrutura do banco de dados. Ele cria as tabelas `leagues` e `teams` e as preenche com todos os dados de produtos da aplicação. Também adiciona a coluna `payment_method` à tabela `orders` e aplica uma correção de segurança a uma função existente. Nenhum dado de usuário ou pedido existente será perdido.

          ## Metadata:
          - Schema-Category: ["Structural", "Data"]
          - Impact-Level: ["Medium"]
          - Requires-Backup: false
          - Reversible: false
          
          ## Structure Details:
          - Cria a tabela `leagues`.
          - Cria a tabela `teams`.
          - Insere 7 registros em `leagues`.
          - Insere 105 registros em `teams`.
          - Altera a tabela `orders` para adicionar a coluna `payment_method`.
          - Altera a função `handle_new_user` para definir o `search_path`.
          
          ## Security Implications:
          - RLS Status: Habilitado para as novas tabelas.
          - Policy Changes: Sim, adiciona políticas de leitura pública para `leagues` e `teams`.
          - Auth Requirements: N/A
          
          ## Performance Impact:
          - Indexes: Adiciona chaves primárias e estrangeiras que são indexadas por padrão.
          - Triggers: Nenhum novo gatilho.
          - Estimated Impact: Baixo. As operações são de configuração inicial.
          */

-- 1. Criar a tabela de Ligas
CREATE TABLE public.leagues (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text NOT NULL,
    slug text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT leagues_pkey PRIMARY KEY (id),
    CONSTRAINT leagues_name_key UNIQUE (name),
    CONSTRAINT leagues_slug_key UNIQUE (slug)
);

-- 2. Criar a tabela de Times
CREATE TABLE public.teams (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text NOT NULL,
    price numeric NOT NULL,
    image1 text NOT NULL,
    image2 text NOT NULL,
    league_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT teams_pkey PRIMARY KEY (id),
    CONSTRAINT teams_league_id_fkey FOREIGN KEY (league_id) REFERENCES public.leagues(id) ON DELETE CASCADE
);

-- 3. Habilitar RLS e criar políticas de leitura pública
ALTER TABLE public.leagues ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to leagues" ON public.leagues FOR SELECT USING (true);

ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to teams" ON public.teams FOR SELECT USING (true);

-- 4. Inserir os dados das Ligas
INSERT INTO public.leagues (slug, name) VALUES
    ('brasileirao', 'Brasileirão A'),
    ('laliga', 'La Liga'),
    ('premier', 'Premier League'),
    ('seriea', 'Série A Italiana'),
    ('ligue1', 'Ligue 1'),
    ('liganos', 'Liga Portugal');

-- 5. Inserir os dados dos Times
DO $$
DECLARE
    brasileirao_id uuid;
    laliga_id uuid;
    premier_id uuid;
    seriea_id uuid;
    ligue1_id uuid;
    liganos_id uuid;
BEGIN
    SELECT id INTO brasileirao_id FROM public.leagues WHERE slug = 'brasileirao';
    SELECT id INTO laliga_id FROM public.leagues WHERE slug = 'laliga';
    SELECT id INTO premier_id FROM public.leagues WHERE slug = 'premier';
    SELECT id INTO seriea_id FROM public.leagues WHERE slug = 'seriea';
    SELECT id INTO ligue1_id FROM public.leagues WHERE slug = 'ligue1';
    SELECT id INTO liganos_id FROM public.leagues WHERE slug = 'liganos';

    -- Brasileirão A
    INSERT INTO public.teams (name, league_id, image1, image2, price) VALUES
      ('Flamengo', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Flamengo+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Flamengo+Away', 89.90),
      ('Palmeiras', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/16a34a/ffffff?text=Palmeiras+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/16a34a?text=Palmeiras+Away', 89.90),
      ('Corinthians', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Corinthians+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Corinthians+Away', 89.90),
      ('Santos', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Santos+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Santos+Away', 89.90),
      ('São Paulo', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=São+Paulo+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=São+Paulo+Away', 89.90),
      ('Grêmio', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Grêmio+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=Grêmio+Away', 89.90),
      ('Internacional', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Internacional+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Internacional+Away', 89.90),
      ('Atlético-MG', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Atlético-MG+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Atlético-MG+Away', 89.90),
      ('Botafogo', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Botafogo+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Botafogo+Away', 89.90),
      ('Fluminense', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/16a34a/ffffff?text=Fluminense+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Fluminense+Away', 89.90),
      ('Vasco', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Vasco+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Vasco+Away', 89.90),
      ('Cruzeiro', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Cruzeiro+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=Cruzeiro+Away', 89.90),
      ('Bahia', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Bahia+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Bahia+Away', 89.90),
      ('Fortaleza', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Fortaleza+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Fortaleza+Away', 89.90),
      ('Athletico-PR', brasileirao_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Athletico-PR+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Athletico-PR+Away', 89.90);

    -- La Liga
    INSERT INTO public.teams (name, league_id, image1, image2, price) VALUES
      ('Real Madrid', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Real+Madrid+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Real+Madrid+Away', 109.90),
      ('Barcelona', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/2563eb?text=Barcelona+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Barcelona+Away', 109.90),
      ('Atlético Madrid', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Atlético+Madrid+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Atlético+Madrid+Away', 109.90),
      ('Sevilla', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Sevilla+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Sevilla+Away', 109.90),
      ('Valencia', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Valencia+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Valencia+Away', 109.90),
      ('Villarreal', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/eab308/000000?text=Villarreal+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Villarreal+Away', 109.90),
      ('Real Sociedad', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Real+Sociedad+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=Real+Sociedad+Away', 109.90),
      ('Real Betis', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/16a34a/ffffff?text=Real+Betis+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Real+Betis+Away', 109.90),
      ('Athletic Bilbao', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Athletic+Bilbao+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Athletic+Bilbao+Away', 109.90),
      ('Celta Vigo', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/87ceeb/ffffff?text=Celta+Vigo+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/87ceeb?text=Celta+Vigo+Away', 109.90),
      ('Espanyol', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Espanyol+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=Espanyol+Away', 109.90),
      ('Getafe', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Getafe+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Getafe+Away', 109.90),
      ('Granada', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Granada+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Granada+Away', 109.90),
      ('Osasuna', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Osasuna+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Osasuna+Away', 109.90),
      ('Rayo Vallecano', laliga_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Rayo+Vallecano+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Rayo+Vallecano+Away', 109.90);

    -- Premier League
    INSERT INTO public.teams (name, league_id, image1, image2, price) VALUES
      ('Manchester City', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/87ceeb/ffffff?text=Manchester+City+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Manchester+City+Away', 119.90),
      ('Manchester United', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Manchester+United+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Manchester+United+Away', 119.90),
      ('Liverpool', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Liverpool+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Liverpool+Away', 119.90),
      ('Chelsea', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Chelsea+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/eab308/000000?text=Chelsea+Away', 119.90),
      ('Arsenal', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Arsenal+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/eab308/000000?text=Arsenal+Away', 119.90),
      ('Tottenham', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Tottenham+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Tottenham+Away', 119.90),
      ('Leicester City', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Leicester+City+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=Leicester+City+Away', 119.90),
      ('West Ham', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/800080/ffffff?text=West+Ham+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=West+Ham+Away', 119.90),
      ('Everton', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Everton+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=Everton+Away', 119.90),
      ('Wolverhampton', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/eab308/000000?text=Wolverhampton+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Wolverhampton+Away', 119.90),
      ('Aston Villa', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/800080/ffffff?text=Aston+Villa+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Aston+Villa+Away', 119.90),
      ('Leeds United', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Leeds+United+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Leeds+United+Away', 119.90),
      ('Newcastle', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Newcastle+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Newcastle+Away', 119.90),
      ('Brighton', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Brighton+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/eab308/000000?text=Brighton+Away', 119.90),
      ('Crystal Palace', premier_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/2563eb?text=Crystal+Palace+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Crystal+Palace+Away', 119.90);

    -- Série A Italiana
    INSERT INTO public.teams (name, league_id, image1, image2, price) VALUES
      ('Juventus', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Juventus+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Juventus+Away', 109.90),
      ('Inter de Milão', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/000000?text=Inter+Milano+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=Inter+Milano+Away', 109.90),
      ('AC Milan', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/000000?text=AC+Milan+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=AC+Milan+Away', 109.90),
      ('Napoli', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Napoli+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=Napoli+Away', 109.90),
      ('AS Roma', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/eab308?text=AS+Roma+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=AS+Roma+Away', 109.90),
      ('Lazio', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/87ceeb/ffffff?text=Lazio+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/87ceeb?text=Lazio+Away', 109.90),
      ('Atalanta', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/000000?text=Atalanta+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=Atalanta+Away', 109.90),
      ('Fiorentina', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/800080/ffffff?text=Fiorentina+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/800080?text=Fiorentina+Away', 109.90),
      ('Torino', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/800080/ffffff?text=Torino+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/800080?text=Torino+Away', 109.90),
      ('Sassuolo', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/16a34a/000000?text=Sassuolo+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Sassuolo+Away', 109.90),
      ('Udinese', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Udinese+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Udinese+Away', 109.90),
      ('Bologna', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/2563eb?text=Bologna+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Bologna+Away', 109.90),
      ('Sampdoria', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/dc2626?text=Sampdoria+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=Sampdoria+Away', 109.90),
      ('Genoa', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/2563eb?text=Genoa+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Genoa+Away', 109.90),
      ('Hellas Verona', seriea_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/eab308?text=Hellas+Verona+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=Hellas+Verona+Away', 109.90);

    -- Ligue 1
    INSERT INTO public.teams (name, league_id, image1, image2, price) VALUES
      ('PSG', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/dc2626?text=PSG+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=PSG+Away', 109.90),
      ('Marseille', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/87ceeb?text=Marseille+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/87ceeb/ffffff?text=Marseille+Away', 109.90),
      ('Lyon', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Lyon+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Lyon+Away', 109.90),
      ('Lille', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Lille+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Lille+Away', 109.90),
      ('Monaco', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Monaco+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Monaco+Away', 109.90),
      ('Nice', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/000000?text=Nice+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Nice+Away', 109.90),
      ('Rennes', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/000000?text=Rennes+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Rennes+Away', 109.90),
      ('Strasbourg', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Strasbourg+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=Strasbourg+Away', 109.90),
      ('Montpellier', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/eab308?text=Montpellier+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=Montpellier+Away', 109.90),
      ('Nantes', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/eab308/16a34a?text=Nantes+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/eab308?text=Nantes+Away', 109.90),
      ('Bordeaux', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/2563eb?text=Bordeaux+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Bordeaux+Away', 109.90),
      ('Saint-Étienne', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/16a34a/ffffff?text=Saint-Étienne+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/16a34a?text=Saint-Étienne+Away', 109.90),
      ('Lens', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/eab308/dc2626?text=Lens+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/eab308?text=Lens+Away', 109.90),
      ('Reims', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Reims+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Reims+Away', 109.90),
      ('Angers', ligue1_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Angers+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Angers+Away', 109.90);

    -- Liga Portugal
    INSERT INTO public.teams (name, league_id, image1, image2, price) VALUES
      ('FC Porto', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=FC+Porto+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=FC+Porto+Away', 99.90),
      ('Benfica', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Benfica+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Benfica+Away', 99.90),
      ('Sporting', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/16a34a/ffffff?text=Sporting+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/16a34a?text=Sporting+Away', 99.90),
      ('SC Braga', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=SC+Braga+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=SC+Braga+Away', 99.90),
      ('Vitória SC', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Vitória+SC+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Vitória+SC+Away', 99.90),
      ('Famalicão', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/2563eb/ffffff?text=Famalicão+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/2563eb?text=Famalicão+Away', 99.90),
      ('Gil Vicente', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/eab308?text=Gil+Vicente+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Gil+Vicente+Away', 99.90),
      ('Moreirense', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/16a34a/ffffff?text=Moreirense+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/16a34a?text=Moreirense+Away', 99.90),
      ('Paços Ferreira', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/eab308/16a34a?text=Paços+Ferreira+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/eab308?text=Paços+Ferreira+Away', 99.90),
      ('Rio Ave', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/16a34a/ffffff?text=Rio+Ave+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/16a34a?text=Rio+Ave+Away', 99.90),
      ('Santa Clara', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/dc2626/ffffff?text=Santa+Clara+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/dc2626?text=Santa+Clara+Away', 99.90),
      ('Tondela', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/eab308/16a34a?text=Tondela+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/eab308?text=Tondela+Away', 99.90),
      ('Vizela', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Vizela+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Vizela+Away', 99.90),
      ('Arouca', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/eab308/000000?text=Arouca+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/eab308?text=Arouca+Away', 99.90),
      ('Boavista', liganos_id, 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/000000/ffffff?text=Boavista+Home', 'https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://img-wrapper.vercel.app/image?url=https://placehold.co/300x350/ffffff/000000?text=Boavista+Away', 99.90);

END $$;

-- 6. Adicionar coluna de método de pagamento aos pedidos
ALTER TABLE public.orders ADD COLUMN payment_method text;

-- 7. Corrigir o search_path da função para maior segurança
ALTER FUNCTION public.handle_new_user() SET search_path = public;
